package com.fluidtouch.noteshelf.documentframework.FTNoteshelfDocument;

public enum FTDocumentType {
    defaultType, diary, weeklyPlanner, dailyAndWeeklyPlanner, autoGeneratedDiary, dynamicTemplate
}
