package com.fluidtouch.noteshelf.documentframework.FTNoteshelfDocument;

import com.fluidtouch.noteshelf.documentframework.FTUrl;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class FTDocumentPostProcessOperation {
    public interface FTPostProcess {
        void perform();
    }

    public static FTPostProcess operation(FTDocumentInputInfo info, FTUrl url) {
        FTPostProcess operation = null;

        if (info.postProcessInfo.documentType == FTDocumentType.autoGeneratedDiary) {
            operation = new FTDocumentDigitalDiaryPostOperation(url, info);
        }
        return operation;
    }

    //To find index of current date for Diaries of type .dailyAndWeeklyPlanner
   /* int dayIndex(Date date) {
        Calendar currentDate = new GregorianCalendar();
        let comp = calendar.components(.day, from:currentDate, to:date, options:[])
        let totalDays = abs(comp.day ? ? 0);
        return 76 + totalDays + 1;
    }*/
}
